const $=s=>document.querySelector(s),store={get:(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const tools=[
{id:'qr',cat:'文本工具',icon:'▦',name:'二维码生成',desc:'将文字、网址快速生成二维码',keys:'qr code 文字转二维码',render:qrTool},{id:'qr-read',cat:'文本工具',icon:'⌗',name:'二维码识别',desc:'从图片中读取二维码内容',keys:'扫描 解析 qr',render:qrReadTool},{id:'json',cat:'开发工具',icon:'{}',name:'JSON 格式化',desc:'格式化、压缩与校验 JSON',keys:'json beautify minify',render:jsonTool},{id:'base64',cat:'编码工具',icon:'B64',name:'Base64 编解码',desc:'文本与 Base64 双向转换',keys:'base64 encode decode',render:base64Tool},{id:'url',cat:'编码工具',icon:'%',name:'URL 编解码',desc:'URL 参数编码和解码',keys:'url encode decode',render:urlTool},{id:'timestamp',cat:'时间工具',icon:'◷',name:'时间戳转换',desc:'时间戳与日期时间相互转换',keys:'unix timestamp 日期',render:timestampTool},{id:'cron',cat:'时间工具',icon:'⏱',name:'Cron 生成器',desc:'可视化生成常用 Cron 表达式',keys:'cron 定时任务 linux',render:cronTool},{id:'uuid',cat:'开发工具',icon:'#',name:'UUID 生成',desc:'批量生成 UUID v4',keys:'uuid guid random',render:uuidTool},{id:'jwt',cat:'开发工具',icon:'JWT',name:'JWT 解析',desc:'本地解析 Header 与 Payload',keys:'jwt token decoder',render:jwtTool},{id:'hash',cat:'开发工具',icon:'⌁',name:'SHA 哈希',desc:'生成 SHA-1、SHA-256、SHA-512',keys:'hash sha digest',render:hashTool},{id:'regex',cat:'开发工具',icon:'.*',name:'正则测试',desc:'实时测试正则表达式与匹配结果',keys:'regex regexp 正则',render:regexTool},{id:'markdown',cat:'文本工具',icon:'M↓',name:'Markdown 预览',desc:'实时渲染 Markdown 文本',keys:'markdown md html',render:markdownTool},{id:'image-compress',cat:'图片工具',icon:'◫',name:'图片压缩',desc:'本地压缩 JPG、PNG、WebP',keys:'图片 压缩 image compress',render:imageCompressTool},{id:'image-convert',cat:'图片工具',icon:'↻',name:'图片格式转换',desc:'图片转换为 JPG、PNG 或 WebP',keys:'webp jpg png convert',render:imageConvertTool},{id:'date-calc',cat:'时间工具',icon:'▣',name:'日期计算',desc:'计算两个日期之间相差天数',keys:'date days 日期计算',render:dateCalcTool},{id:'text-stats',cat:'文本工具',icon:'字',name:'字数统计',desc:'统计字符、字数、行数和空格',keys:'word count 字数',render:textStatsTool},{id:'case',cat:'文本工具',icon:'Aa',name:'大小写转换',desc:'英文大小写及标题格式转换',keys:'uppercase lowercase case',render:caseTool},{id:'color',cat:'设计工具',icon:'◉',name:'颜色转换',desc:'HEX 与 RGB 颜色互转',keys:'color hex rgb 颜色',render:colorTool}
];
const cats=['首页',...new Set(tools.map(t=>t.cat))];let current=null;
function init(){$('#count').textContent=tools.length;renderNav();renderHome();bind();if(store.get('theme','light')==='dark')toggleTheme(true);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});route()}
function bind(){$('#search').addEventListener('input',e=>renderHome(e.target.value));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#backBtn').onclick=()=>history.pushState({},'',location.pathname);$('#themeBtn').onclick=()=>toggleTheme();document.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea/i.test(e.target.tagName)){e.preventDefault();$('#search').focus()}});window.onpopstate=route}
function renderNav(){$('#nav').innerHTML=cats.map(c=>`<button data-cat="${c}">${c==='首页'?'⌂':'•'} ${c}</button>`).join('');$('#nav').onclick=e=>{const b=e.target.closest('button');if(!b)return;$('#search').value=b.dataset.cat==='首页'?'':b.dataset.cat;renderHome($('#search').value);showHome();$('#sidebar').classList.remove('open')}}
function renderHome(q=''){const term=q.trim().toLowerCase(),list=tools.filter(t=>!term||`${t.name} ${t.desc} ${t.cat} ${t.keys}`.toLowerCase().includes(term));$('#resultCount').textContent=`${list.length} 个`;$('#sections').innerHTML=[...new Set(list.map(t=>t.cat))].map(c=>`<div class="category"><div class="section-title"><h2>${c}</h2></div><div class="grid">${list.filter(t=>t.cat===c).map(card).join('')}</div></div>`).join('')||'<p>没有找到相关工具。</p>';renderSaved();bindCards()}
function card(t){const fav=store.get('favorites').includes(t.id);return `<article class="card" data-id="${t.id}"><button class="star ${fav?'on':''}" data-fav="${t.id}">${fav?'★':'☆'}</button><div class="icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p></article>`}
function bindCards(){document.querySelectorAll('.card').forEach(x=>x.onclick=e=>{if(e.target.dataset.fav)return toggleFav(e.target.dataset.fav);openTool(x.dataset.id)})}
function renderSaved(){const fs=store.get('favorites'),rs=store.get('recent');$('#favorites').innerHTML=fs.length?fs.map(id=>tools.find(t=>t.id===id)).filter(Boolean).map(card).join(''):'<p>点击工具卡片右上角的 ☆ 添加收藏。</p>';$('#recent').innerHTML=rs.length?rs.map(id=>tools.find(t=>t.id===id)).filter(Boolean).map(card).join(''):'<p>使用过的工具会显示在这里。</p>'}
function toggleFav(id){let a=store.get('favorites');a=a.includes(id)?a.filter(x=>x!==id):[id,...a];store.set('favorites',a);renderHome($('#search').value);if(current===id)updateFavButton()}
function openTool(id){history.pushState({},'',`?tool=${id}`);route()}
function route(){const id=new URLSearchParams(location.search).get('tool');id&&tools.some(t=>t.id===id)?showTool(id):showHome()}
function showHome(){$('#hero').classList.remove('hidden');$('#home').classList.remove('hidden');$('#toolView').classList.add('hidden');current=null;scrollTo(0,0)}
function showTool(id){const t=tools.find(x=>x.id===id);current=id;$('#hero').classList.add('hidden');$('#home').classList.add('hidden');$('#toolView').classList.remove('hidden');$('#toolCat').textContent=t.cat;$('#toolTitle').textContent=t.name;$('#toolDesc').textContent=t.desc;$('#toolBody').innerHTML='';t.render($('#toolBody'));let r=store.get('recent').filter(x=>x!==id);store.set('recent',[id,...r].slice(0,8));updateFavButton();$('#favBtn').onclick=()=>toggleFav(id);scrollTo(0,0)}
function updateFavButton(){const on=store.get('favorites').includes(current);$('#favBtn').textContent=on?'★ 已收藏':'☆ 收藏'}
function toggleTheme(force){const dark=force??!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);store.set('theme',dark?'dark':'light');$('#themeBtn').textContent=dark?'☀️ 浅色模式':'🌙 深色模式'}
function toast(s){const x=$('#toast');x.textContent=s;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1600)}
function panel(input='输入',output='结果'){return `<div class="tool-grid"><div class="box"><label>${input}</label><textarea id="input"></textarea><div id="controls" class="actions"></div></div><div class="box"><label>${output}</label><div id="output" class="output"></div><div id="outActions" class="actions"></div></div></div>`}
function copy(s){navigator.clipboard.writeText(s).then(()=>toast('已复制'))}
function qrTool(el){el.innerHTML=`<div class="tool-grid"><div class="box"><label>二维码内容</label><textarea id="qrText">https://example.com</textarea><label>尺寸</label><select id="qrSize"><option>256</option><option>512</option><option>1024</option></select><div class="actions"><button class="primary" id="go">生成二维码</button></div></div><div class="box" style="text-align:center"><canvas id="qrCanvas" class="preview"></canvas><div class="actions"><button class="secondary" id="download">下载 PNG</button></div></div></div>`;const go=()=>QRCode.toCanvas($('#qrCanvas'),$('#qrText').value,{width:+$('#qrSize').value,margin:2},e=>e&&toast('生成失败'));$('#go').onclick=go;$('#download').onclick=()=>{const a=document.createElement('a');a.download='qrcode.png';a.href=$('#qrCanvas').toDataURL();a.click()};go()}
function qrReadTool(el){el.innerHTML=`<div class="drop"><input type="file" id="file" accept="image/*"><p>选择包含二维码的图片</p></div><div class="box" style="margin-top:16px"><label>识别结果</label><div id="output" class="output">等待上传图片</div></div>`;$('#file').onchange=e=>readImage(e.target.files[0],img=>{const c=document.createElement('canvas'),x=c.getContext('2d');c.width=img.width;c.height=img.height;x.drawImage(img,0,0);const d=x.getImageData(0,0,c.width,c.height),r=jsQR(d.data,c.width,c.height);$('#output').textContent=r?r.data:'未识别到二维码'})}
function jsonTool(el){el.innerHTML=panel('JSON 输入','格式化结果');$('#input').placeholder='{"name":"Suria Tools"}';$('#controls').innerHTML='<button class="primary" id="format">格式化</button><button class="secondary" id="minify">压缩</button>';const run=n=>{try{$('#output').textContent=JSON.stringify(JSON.parse($('#input').value),null,n);toast('处理完成')}catch(e){$('#output').textContent='JSON 错误：'+e.message}};$('#format').onclick=()=>run(2);$('#minify').onclick=()=>run(0)}
function base64Tool(el){el.innerHTML=panel('文本或 Base64','转换结果');$('#controls').innerHTML='<button class="primary" id="enc">编码</button><button class="secondary" id="dec">解码</button>';$('#enc').onclick=()=>$('#output').textContent=btoa(unescape(encodeURIComponent($('#input').value)));$('#dec').onclick=()=>{try{$('#output').textContent=decodeURIComponent(escape(atob($('#input').value.trim())))}catch{$('#output').textContent='无法解码，请检查内容'}}}
function urlTool(el){el.innerHTML=panel('文本或 URL','转换结果');$('#controls').innerHTML='<button class="primary" id="enc">编码</button><button class="secondary" id="dec">解码</button>';$('#enc').onclick=()=>$('#output').textContent=encodeURIComponent($('#input').value);$('#dec').onclick=()=>{try{$('#output').textContent=decodeURIComponent($('#input').value)}catch{$('#output').textContent='解码失败'}}}
function timestampTool(el){el.innerHTML=`<div class="tool-grid"><div class="box"><label>时间戳（秒或毫秒）</label><input id="ts" value="${Date.now()}"><div class="actions"><button id="toDate" class="primary">转日期</button></div></div><div class="box"><label>日期时间</label><input id="date" type="datetime-local"><div class="actions"><button id="toTs" class="primary">转时间戳</button></div><div id="output" class="output"></div></div></div>`;$('#toDate').onclick=()=>{let n=Number($('#ts').value);if(String(Math.trunc(n)).length<=10)n*=1000;const d=new Date(n);$('#output').textContent=isNaN(d)?'无效时间戳':`${d.toLocaleString()}\nISO: ${d.toISOString()}`};$('#toTs').onclick=()=>{const n=new Date($('#date').value).getTime();$('#output').textContent=`毫秒：${n}\n秒：${Math.floor(n/1000)}`}}
function cronTool(el){el.innerHTML=`<div class="box"><label>执行频率</label><select id="freq"><option value="* * * * *">每分钟</option><option value="0 * * * *">每小时</option><option value="0 0 * * *">每天 00:00</option><option value="0 9 * * 1-5">工作日 09:00</option><option value="0 0 * * 0">每周日 00:00</option><option value="0 0 1 * *">每月 1 日 00:00</option></select><div class="box" style="margin-top:16px"><label>Cron 表达式</label><div id="output" class="output"></div></div></div>`;const r=()=>$('#output').textContent=$('#freq').value;$('#freq').onchange=r;r()}
function uuidTool(el){el.innerHTML=`<div class="box"><label>生成数量</label><input id="num" type="number" min="1" max="100" value="5"><div class="actions"><button class="primary" id="go">生成</button><button class="secondary" id="cp">复制全部</button></div><pre id="output" class="output"></pre></div>`;const go=()=>$('#output').textContent=Array.from({length:Math.min(100,+$('#num').value||1)},()=>crypto.randomUUID()).join('\n');$('#go').onclick=go;$('#cp').onclick=()=>copy($('#output').textContent);go()}
function jwtTool(el){el.innerHTML=panel('JWT Token','解析结果');$('#controls').innerHTML='<button class="primary" id="go">解析</button>';$('#go').onclick=()=>{try{const [h,p]=$('#input').value.trim().split('.'),dec=s=>JSON.parse(decodeURIComponent(escape(atob(s.replace(/-/g,'+').replace(/_/g,'/')))));$('#output').textContent='Header\n'+JSON.stringify(dec(h),null,2)+'\n\nPayload\n'+JSON.stringify(dec(p),null,2)}catch{$('#output').textContent='JWT 格式无效'}}}
function hashTool(el){el.innerHTML=panel('待计算文本','哈希结果');$('#controls').innerHTML='<button class="primary" data-a="SHA-256">SHA-256</button><button class="secondary" data-a="SHA-1">SHA-1</button><button class="secondary" data-a="SHA-512">SHA-512</button>';$('#controls').onclick=async e=>{if(!e.target.dataset.a)return;const b=await crypto.subtle.digest(e.target.dataset.a,new TextEncoder().encode($('#input').value));$('#output').textContent=[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}}
function regexTool(el){el.innerHTML=`<div class="box"><label>正则表达式</label><input id="pattern" placeholder="例如：\\d+"><label>测试文本</label><textarea id="input"></textarea><div class="actions"><button class="primary" id="go">测试</button></div><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{try{const r=new RegExp($('#pattern').value,'g'),m=[...$('#input').value.matchAll(r)].map(x=>x[0]);$('#output').textContent=m.length?`匹配 ${m.length} 项：\n${m.join('\n')}`:'没有匹配'}catch(e){$('#output').textContent=e.message}}}
function markdownTool(el){el.innerHTML=panel('Markdown','预览');$('#input').value='# Suria Tools\n\n这是一个 **Markdown** 预览工具。';const r=()=>$('#output').innerHTML=marked.parse($('#input').value);$('#input').oninput=r;r()}
function imageCompressTool(el){imageTool(el,true)}function imageConvertTool(el){imageTool(el,false)}
function imageTool(el,compress){el.innerHTML=`<div class="tool-grid"><div class="box"><input id="file" type="file" accept="image/*"><label>输出格式</label><select id="fmt"><option value="image/webp">WebP</option><option value="image/jpeg">JPG</option><option value="image/png">PNG</option></select><label>质量：<span id="qv">80</span>%</label><input id="quality" type="range" min="10" max="100" value="80"><div class="actions"><button id="go" class="primary">${compress?'压缩':'转换'}</button></div></div><div class="box"><img id="preview" class="preview"><div id="info" class="output"></div><div class="actions"><button id="down" class="secondary hidden">下载图片</button></div></div></div>`;let img,file,url;$('#quality').oninput=e=>$('#qv').textContent=e.target.value;$('#file').onchange=e=>{file=e.target.files[0];readImage(file,x=>{img=x;$('#preview').src=x.src})};$('#go').onclick=()=>{if(!img)return toast('请先选择图片');const c=document.createElement('canvas');c.width=img.width;c.height=img.height;c.getContext('2d').drawImage(img,0,0);c.toBlob(b=>{url=URL.createObjectURL(b);$('#preview').src=url;$('#info').textContent=`原始：${fmtSize(file.size)}\n输出：${fmtSize(b.size)}${compress?`\n减少：${Math.max(0,Math.round((1-b.size/file.size)*100))}%`:''}`;$('#down').classList.remove('hidden');$('#down').onclick=()=>{const a=document.createElement('a');a.href=url;a.download=`suria-tools.${$('#fmt').value.split('/')[1].replace('jpeg','jpg')}`;a.click()}},$('#fmt').value,+$('#quality').value/100)}}
function dateCalcTool(el){el.innerHTML=`<div class="tool-grid"><div class="box"><label>开始日期</label><input id="a" type="date"><label>结束日期</label><input id="b" type="date"><button id="go" class="primary">计算</button></div><div class="box"><div id="output" class="output">请选择日期</div></div></div>`;$('#go').onclick=()=>{const a=new Date($('#a').value),b=new Date($('#b').value);$('#output').textContent=isNaN(a)||isNaN(b)?'请选择完整日期':`相差 ${Math.abs(Math.round((b-a)/86400000))} 天`}}
function textStatsTool(el){el.innerHTML=panel('输入文本','统计结果');const r=()=>{const s=$('#input').value;$('#output').textContent=`字符：${s.length}\n非空字符：${s.replace(/\s/g,'').length}\n单词：${(s.trim().match(/[A-Za-z0-9]+|[\u4e00-\u9fff]/g)||[]).length}\n行数：${s?s.split('\n').length:0}\n空格：${(s.match(/ /g)||[]).length}`};$('#input').oninput=r;r()}
function caseTool(el){el.innerHTML=panel('英文文本','转换结果');$('#controls').innerHTML='<button class="primary" data-t="upper">大写</button><button class="secondary" data-t="lower">小写</button><button class="secondary" data-t="title">标题格式</button>';$('#controls').onclick=e=>{const s=$('#input').value,t=e.target.dataset.t;if(t==='upper')$('#output').textContent=s.toUpperCase();if(t==='lower')$('#output').textContent=s.toLowerCase();if(t==='title')$('#output').textContent=s.toLowerCase().replace(/\b\w/g,x=>x.toUpperCase())}}
function colorTool(el){el.innerHTML=`<div class="tool-grid"><div class="box"><label>选择颜色</label><input id="picker" type="color" value="#ff6f91"><label>HEX</label><input id="hex" value="#ff6f91"></div><div class="box"><div id="swatch" style="height:120px;border-radius:14px"></div><div id="output" class="output"></div></div></div>`;const r=h=>{if(!/^#[0-9a-f]{6}$/i.test(h))return;const n=parseInt(h.slice(1),16),rgb=[n>>16,(n>>8)&255,n&255];$('#picker').value=h;$('#hex').value=h;$('#swatch').style.background=h;$('#output').textContent=`HEX: ${h.toUpperCase()}\nRGB: rgb(${rgb.join(', ')})`};$('#picker').oninput=e=>r(e.target.value);$('#hex').oninput=e=>r(e.target.value);r('#ff6f91')}
function readImage(file,cb){if(!file)return;const img=new Image;img.onload=()=>cb(img);img.src=URL.createObjectURL(file)}function fmtSize(n){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(2)} MB`}
init();