/* Suria Tools 扩展模块：新增工具只需在此注册，无需修改核心。 */
function X(id,cat,icon,name,desc,keys,render){tools.push(T(id,cat,icon,name,desc,keys,render));if(!categories.includes(cat))categories.push(cat)}
function xText(fn,labels=['处理']){return el=>{el.innerHTML=panel();$('#controls').innerHTML=labels.map((x,i)=>`<button class="${i?'secondary':'primary'}" data-i="${i}">${x}</button>`).join('');$('#controls').onclick=e=>{if(e.target.dataset.i===undefined)return;try{$('#output').textContent=fn($('#input').value,+e.target.dataset.i)}catch(x){$('#output').textContent=x.message}}}}
X('trim-lines','文本工具','⌫','清理空白','清理行首行尾空格和多余空行','trim whitespace',xText(s=>s.split(/\r?\n/).map(x=>x.trim()).filter((x,i,a)=>x||a[i-1]).join('\n')));
X('replace','文本工具','⇄','批量替换','查找并替换全部匹配文本','find replace',el=>{el.innerHTML=`<div class="panel"><textarea id="input"></textarea><div class="form-grid"><input id="find" placeholder="查找"><input id="rep" placeholder="替换为"></div><button id="go" class="primary">替换</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>$('#output').textContent=$('#input').value.split($('#find').value).join($('#rep').value)});
X('prefix-suffix','文本工具','±','前后缀处理','为每行添加前缀和后缀','prefix suffix',el=>{el.innerHTML=`<div class="panel"><textarea id="input"></textarea><div class="form-grid"><input id="pre" placeholder="前缀"><input id="suf" placeholder="后缀"></div><button id="go" class="primary">处理</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>$('#output').textContent=$('#input').value.split(/\r?\n/).map(x=>$('#pre').value+x+$('#suf').value).join('\n')});
X('reverse','文本工具','↶','文本反转','反转字符、单词或行','reverse text',xText((s,i)=>i===0?[...s].reverse().join(''):i===1?s.split(/\s+/).reverse().join(' '):s.split(/\r?\n/).reverse().join('\n'),['字符反转','单词反转','行反转']));
X('slug','文本工具','/','Slug 生成','标题转换为 URL Slug','slug url',xText(s=>s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'')));
X('char-frequency','文本工具','频','字符频率','统计非空字符出现次数','frequency',xText(s=>{const m={};[...s].filter(x=>!/\s/.test(x)).forEach(c=>m[c]=(m[c]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1]).map(x=>`${x[0]}：${x[1]}`).join('\n')}));
X('hex-text','编码工具','0x','Hex 文本转换','文本与十六进制互转','hex string',xText((s,i)=>i===0?[...new TextEncoder().encode(s)].map(x=>x.toString(16).padStart(2,'0')).join(' '):new TextDecoder().decode(new Uint8Array(s.trim().split(/\s+/).map(x=>parseInt(x,16)))),['文本转 Hex','Hex 转文本']));
X('binary-text','编码工具','01','二进制文本','文本与二进制互转','binary string',xText((s,i)=>i===0?[...new TextEncoder().encode(s)].map(x=>x.toString(2).padStart(8,'0')).join(' '):new TextDecoder().decode(new Uint8Array(s.trim().split(/\s+/).map(x=>parseInt(x,2)))),['文本转二进制','二进制转文本']));
X('json-string','编码工具','J"','JSON 字符串转义','字符串转义和反转义','json escape',xText((s,i)=>i===0?JSON.stringify(s).slice(1,-1):JSON.parse(`"${s.replace(/"/g,'\\"')}"`),['转义','反转义']));
X('uri-full','编码工具','URI','完整 URI 编解码','使用 encodeURI 和 decodeURI','uri encode',xText((s,i)=>i===0?encodeURI(s):decodeURI(s),['编码','解码']));
X('base64-image','编码工具','图64','图片 Base64','图片转换为 Data URL','image base64',extraBase64Image);
X('curl-axios','开发工具','Ax','Curl 转 Axios','Curl 转 Axios 配置','curl axios',extraCurl('axios'));
X('curl-python','开发工具','Py','Curl 转 Python','Curl 转 requests','curl python',extraCurl('python'));
X('env-json','开发工具','.env','.env / JSON','环境变量和 JSON 双向转换','env json',extraEnv);
X('json-path','开发工具','$.','JSON 路径提取','按点路径读取 JSON 值','json path',extraJsonPath);
X('number-base','开发工具','进','进制转换','二八十十六进制互转','radix base',extraBase);
X('random-number','开发工具','骰','随机数生成','生成指定范围随机整数','random number',extraRandom);
X('lorem','开发工具','¶','占位文本','生成中文或英文占位段落','lorem ipsum',extraLorem);
X('mime','开发工具','MIME','MIME 查询','查询常见扩展名 MIME','mime type',extraMime);
X('http-status','开发工具','HTTP','HTTP 状态码','查询常见 HTTP 状态码','status code',extraStatus);
X('json-sort','开发工具','JS','JSON 键排序','递归排序 JSON 对象键','json sort',xText(s=>JSON.stringify(extraSort(JSON.parse(s)),null,2)));
X('csv-json','开发工具','CSV','CSV / JSON','简单 CSV 和 JSON 数组互转','csv json',extraCsv);
X('date-add','时间工具','＋日','日期加减','日期增加或减少天数','date add',extraDateAdd);
X('timezone','时间工具','🌐','时区转换','转换常见时区时间','timezone',extraTimezone);
X('week-number','时间工具','周','周数计算','计算日期所在 ISO 周','week number',extraWeek);
X('image-crop-square','图片工具','□','图片居中裁方','裁剪为居中正方形','crop square',extraSquare);
X('favicon','图片工具','ICO','Favicon 生成','生成多尺寸网站图标','favicon icon',extraFavicon);
X('image-info','图片工具','ⓘ','图片信息','查看图片尺寸格式和大小','image info',extraImageInfo);
X('palette','设计工具','🎨','调色板生成','根据主色生成明暗色阶','palette color',extraPalette);
X('contrast','设计工具','◐','颜色对比度','计算 WCAG 对比度','contrast wcag',extraContrast);
X('css-unit','设计工具','px','CSS 单位换算','px、rem、em 互转','css unit',extraCssUnit);
X('query-builder','网络工具','?','查询参数构建','JSON 生成 URL 查询参数','query string',extraQuery);
X('ip-cidr','网络工具','CIDR','IPv4 CIDR 计算','计算网段和广播地址','cidr subnet',extraCidr);
X('prompt-polish','AI 工具','✨','Prompt 结构化','将需求整理成结构化提示词','prompt improve',extraPrompt);
X('prompt-compress','AI 工具','压','Prompt 压缩','清理重复空白和客套表达','prompt compress',xText(s=>s.replace(/\s+/g,' ').replace(/(?:请|帮我|麻烦你)[，,]?/g,'').trim()));
X('token-estimate','AI 工具','T','Token 估算','粗略估算中英文 Token 数','token count',extraToken);
function extraBase64Image(el){el.innerHTML=`<div class="panel"><input id="file" type="file" accept="image/*"><textarea id="output"></textarea><button id="cp" class="secondary">复制</button></div>`;$('#file').onchange=e=>{const r=new FileReader();r.onload=()=>$('#output').value=r.result;r.readAsDataURL(e.target.files[0])};$('#cp').onclick=()=>copy($('#output').value)}
function extraParseCurl(s){const url=(s.match(/https?:\/\/[^\s'"\\]+/)||[])[0]||'',method=(s.match(/-X\s+(\w+)/i)||[])[1]||'GET',headers={};[...s.matchAll(/-H\s+['"]([^:'"]+):\s*([^'"]+)['"]/g)].forEach(m=>headers[m[1]]=m[2]);const body=(s.match(/(?:--data(?:-raw)?|-d)\s+['"]([\s\S]*?)['"](?:\s|$)/)||[])[1];return{url,method,headers,body}}
function extraCurl(type){return el=>{el.innerHTML=panel('Curl','结果');$('#controls').innerHTML='<button id="go" class="primary">转换</button>';$('#go').onclick=()=>{const x=extraParseCurl($('#input').value);$('#output').textContent=type==='axios'?`axios({\n  url: ${JSON.stringify(x.url)},\n  method: ${JSON.stringify(x.method.toLowerCase())},\n  headers: ${JSON.stringify(x.headers,null,2)}${x.body?`,\n  data: ${JSON.stringify(x.body)}`:''}\n});`:`requests.request(${JSON.stringify(x.method)}, ${JSON.stringify(x.url)}, headers=${JSON.stringify(x.headers)}${x.body?`, data=${JSON.stringify(x.body)}`:''})`}}}
function extraEnv(el){el.innerHTML=panel('.env 或 JSON','结果');$('#controls').innerHTML='<button id="a" class="primary">.env → JSON</button><button id="b" class="secondary">JSON → .env</button>';$('#a').onclick=()=>{const o={};$('#input').value.split(/\r?\n/).filter(x=>x&&!x.trim().startsWith('#')).forEach(l=>{const i=l.indexOf('=');if(i>0)o[l.slice(0,i).trim()]=l.slice(i+1).trim().replace(/^['"]|['"]$/g,'')});$('#output').textContent=JSON.stringify(o,null,2)};$('#b').onclick=()=>{try{$('#output').textContent=Object.entries(JSON.parse($('#input').value)).map(([k,v])=>`${k}=${String(v).includes(' ')?JSON.stringify(v):v}`).join('\n')}catch(x){$('#output').textContent=x.message}}}
function extraJsonPath(el){el.innerHTML=`<div class="panel"><textarea id="input"></textarea><input id="path" placeholder="user.profile.name"><button id="go" class="primary">提取</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{try{const v=$('#path').value.split('.').filter(Boolean).reduce((o,k)=>o?.[k],JSON.parse($('#input').value));$('#output').textContent=typeof v==='string'?v:JSON.stringify(v,null,2)}catch(x){$('#output').textContent=x.message}}}
function extraBase(el){el.innerHTML=`<div class="panel"><input id="value" value="255"><select id="from"><option>2</option><option>8</option><option selected>10</option><option>16</option></select><button id="go" class="primary">转换</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{const n=parseInt($('#value').value,+$('#from').value);$('#output').textContent=Number.isNaN(n)?'无效':`二进制：${n.toString(2)}\n八进制：${n.toString(8)}\n十进制：${n}\n十六进制：${n.toString(16).toUpperCase()}`}}
function extraRandom(el){el.innerHTML=`<div class="panel"><div class="form-grid"><input id="min" type="number" value="1"><input id="max" type="number" value="100"></div><input id="num" type="number" value="10"><button id="go" class="primary">生成</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{const a=+$('#min').value,b=+$('#max').value,n=Math.min(1000,+$('#num').value||1);$('#output').textContent=Array.from({length:n},()=>Math.floor(Math.random()*(b-a+1))+a).join(', ')}}
function extraLorem(el){el.innerHTML=`<div class="panel"><input id="num" type="number" value="3"><select id="lang"><option value="zh">中文</option><option value="en">English</option></select><button id="go" class="primary">生成</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{const z='这是用于排版和界面测试的示例文字，可以帮助检查字号、行距和阅读体验。',e='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.';$('#output').textContent=Array.from({length:Math.min(20,+$('#num').value||1)},()=>$('#lang').value==='zh'?z:e).join('\n\n')}}
const EXTRA_MIME={jpg:'image/jpeg',png:'image/png',webp:'image/webp',svg:'image/svg+xml',gif:'image/gif',pdf:'application/pdf',json:'application/json',xml:'application/xml',html:'text/html',css:'text/css',js:'text/javascript',csv:'text/csv',zip:'application/zip',mp3:'audio/mpeg',mp4:'video/mp4'};
function extraMime(el){el.innerHTML=`<div class="panel"><input id="ext" placeholder="png"><button id="go" class="primary">查询</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>$('#output').textContent=EXTRA_MIME[$('#ext').value.toLowerCase().replace('.','')]||'未收录'}
const EXTRA_STATUS={200:'OK',201:'Created',204:'No Content',301:'Moved Permanently',302:'Found',304:'Not Modified',400:'Bad Request',401:'Unauthorized',403:'Forbidden',404:'Not Found',405:'Method Not Allowed',408:'Request Timeout',409:'Conflict',429:'Too Many Requests',500:'Internal Server Error',502:'Bad Gateway',503:'Service Unavailable',504:'Gateway Timeout'};
function extraStatus(el){el.innerHTML=`<div class="panel"><input id="code" value="404"><button id="go" class="primary">查询</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>$('#output').textContent=EXTRA_STATUS[$('#code').value]||'未收录'}
function extraSort(o){if(Array.isArray(o))return o.map(extraSort);if(o&&typeof o==='object')return Object.keys(o).sort().reduce((r,k)=>(r[k]=extraSort(o[k]),r),{});return o}
function extraCsv(el){el.innerHTML=panel('CSV 或 JSON','结果');$('#controls').innerHTML='<button id="a" class="primary">CSV → JSON</button><button id="b" class="secondary">JSON → CSV</button>';$('#a').onclick=()=>{const l=$('#input').value.trim().split(/\r?\n/),h=l.shift().split(',');$('#output').textContent=JSON.stringify(l.map(x=>Object.fromEntries(x.split(',').map((v,i)=>[h[i],v]))),null,2)};$('#b').onclick=()=>{try{const a=JSON.parse($('#input').value),h=[...new Set(a.flatMap(Object.keys))];$('#output').textContent=[h.join(','),...a.map(o=>h.map(k=>JSON.stringify(o[k]??'')).join(','))].join('\n')}catch(x){$('#output').textContent=x.message}}}
function extraDateAdd(el){el.innerHTML=`<div class="panel"><input id="d" type="date"><input id="n" type="number" value="30"><button id="go" class="primary">计算</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{const d=new Date($('#d').value);d.setDate(d.getDate()+(+$('#n').value||0));$('#output').textContent=d.toISOString().slice(0,10)}}
function extraTimezone(el){const z=['Asia/Shanghai','Asia/Tokyo','America/Los_Angeles','America/New_York','Europe/London','Europe/Paris','Australia/Sydney','UTC'];el.innerHTML=`<div class="panel"><input id="d" type="datetime-local"><select id="z">${z.map(x=>`<option>${x}</option>`).join('')}</select><button id="go" class="primary">转换</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>$('#output').textContent=new Intl.DateTimeFormat('zh-CN',{dateStyle:'full',timeStyle:'long',timeZone:$('#z').value}).format(new Date($('#d').value))}
function extraWeek(el){el.innerHTML=`<div class="panel"><input id="d" type="date"><button id="go" class="primary">计算</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{const d=new Date($('#d').value);d.setHours(0,0,0,0);d.setDate(d.getDate()+3-(d.getDay()+6)%7);const w=1+Math.round(((d-new Date(d.getFullYear(),0,4))/86400000-3+(new Date(d.getFullYear(),0,4).getDay()+6)%7)/7);$('#output').textContent=`ISO 第 ${w} 周`}}
function extraSquare(el){el.innerHTML=`<div class="panel"><input id="file" type="file" accept="image/*"><button id="go" class="primary">裁剪并下载</button></div>`;let img;$('#file').onchange=e=>readImage(e.target.files[0],i=>img=i);$('#go').onclick=()=>{if(!img)return;const s=Math.min(img.width,img.height),c=document.createElement('canvas');c.width=c.height=s;c.getContext('2d').drawImage(img,(img.width-s)/2,(img.height-s)/2,s,s,0,0,s,s);c.toBlob(b=>download('square.png',b))}}
function extraFavicon(el){el.innerHTML=`<div class="panel"><input id="file" type="file" accept="image/*"><button id="go" class="primary">生成图标</button></div>`;let img;$('#file').onchange=e=>readImage(e.target.files[0],i=>img=i);$('#go').onclick=()=>{if(!img)return;[16,32,64,180,512].forEach(s=>{const c=document.createElement('canvas');c.width=c.height=s;c.getContext('2d').drawImage(img,0,0,s,s);c.toBlob(b=>download(`icon-${s}.png`,b))})}}
function extraImageInfo(el){el.innerHTML=`<div class="panel"><input id="file" type="file" accept="image/*"><div id="output" class="output"></div></div>`;$('#file').onchange=e=>{const f=e.target.files[0];readImage(f,i=>$('#output').textContent=`名称：${f.name}\n类型：${f.type}\n尺寸：${i.width}×${i.height}\n大小：${(f.size/1024).toFixed(2)} KB`)}}
function extraPalette(el){el.innerHTML=`<div class="panel"><input id="c" value="#ff6f91"><button id="go" class="primary">生成</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{const h=$('#c').value.replace('#',''),n=parseInt(h,16),rgb=[n>>16,n>>8&255,n&255];$('#output').innerHTML=Array.from({length:9},(_,i)=>{const p=(i-4)*.12,v=rgb.map(x=>Math.round(p<0?x*(1+p):x+(255-x)*p)),hex='#'+v.map(x=>x.toString(16).padStart(2,'0')).join('');return `<div style="padding:10px;background:${hex};color:${i<4?'white':'black'}">${hex}</div>`}).join('')}}
function extraLum(h){h=h.replace('#','');if(h.length===3)h=[...h].map(x=>x+x).join('');return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255).map(x=>x<=.03928?x/12.92:((x+.055)/1.055)**2.4).reduce((a,x,i)=>a+x*[.2126,.7152,.0722][i],0)}
function extraContrast(el){el.innerHTML=`<div class="panel"><input id="a" value="#ffffff"><input id="b" value="#202330"><button id="go" class="primary">计算</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{const a=extraLum($('#a').value),b=extraLum($('#b').value),r=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);$('#output').textContent=`对比度：${r.toFixed(2)}:1\n普通文本 AA：${r>=4.5?'通过':'不通过'}\n大文本 AA：${r>=3?'通过':'不通过'}`}}
function extraCssUnit(el){el.innerHTML=`<div class="panel"><input id="base" type="number" value="16"><input id="px" type="number" value="24"><button id="go" class="primary">换算</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>$('#output').textContent=`${$('#px').value}px = ${(+$('#px').value/+$('#base').value).toFixed(4)}rem = ${(+$('#px').value/+$('#base').value).toFixed(4)}em`}
function extraQuery(el){el.innerHTML=panel('JSON 对象','查询字符串');$('#controls').innerHTML='<button id="go" class="primary">生成</button>';$('#go').onclick=()=>{try{$('#output').textContent=new URLSearchParams(JSON.parse($('#input').value)).toString()}catch(x){$('#output').textContent=x.message}}}
function extraIp(ip){return ip.split('.').reduce((a,x)=>(a<<8)+(+x),0)>>>0}function extraIpText(n){return [24,16,8,0].map(s=>(n>>>s)&255).join('.')}
function extraCidr(el){el.innerHTML=`<div class="panel"><input id="cidr" value="192.168.1.10/24"><button id="go" class="primary">计算</button><div id="output" class="output"></div></div>`;$('#go').onclick=()=>{const [ip,p]=$('#cidr').value.split('/'),bits=+p,mask=bits===0?0:(0xffffffff<<(32-bits))>>>0,n=extraIp(ip),net=n&mask,b=(net|(~mask))>>>0;$('#output').textContent=`子网掩码：${extraIpText(mask)}\n网络地址：${extraIpText(net)}\n广播地址：${extraIpText(b)}\n地址数：${2**(32-bits)}`}}
function extraPrompt(el){el.innerHTML=panel('原始需求','结构化 Prompt');$('#controls').innerHTML='<button id="go" class="primary">生成</button>';$('#go').onclick=()=>$('#output').textContent=`角色：你是一名擅长该任务的专业助手。\n\n目标：${$('#input').value.trim()}\n\n要求：\n1. 理解目标和约束。\n2. 输出可直接使用的结果。\n3. 对不确定内容说明假设。\n4. 使用清晰结构。`}
function extraToken(el){el.innerHTML=panel('文本','估算结果');$('#input').oninput=()=>{const s=$('#input').value,z=(s.match(/[\u4e00-\u9fff]/g)||[]).length,e=(s.match(/[A-Za-z0-9]+/g)||[]).join('').length;$('#output').textContent=`字符数：${s.length}\n粗略 Token：${Math.ceil(z*1.1+e/4+(s.length-z-e)/3)}`};$('#input').dispatchEvent(new Event('input'))}
